version: '3'
services:
  langchain-chainlit-chat-app:
    image: langchain-chainlit-chat-app:latest
    build: .
    env_file:
      - .env
    ports:
      - "80:8000"
    working_dir: /home/appuser/app/
    command:
      [
        "chainlit",
        "run",
        "/home/appuser/app/demo_app/main.py"
      ]
